# Generated by Django 4.0.5 on 2022-06-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosInicio',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreImagen', models.CharField(max_length=250)),
                ('marca', models.CharField(max_length=100)),
                ('nombreProducto', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
