# Generated by Django 4.0.5 on 2022-06-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_productosinicio_delete_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosJugueteria',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreImagen', models.CharField(max_length=250)),
                ('marca', models.CharField(max_length=100)),
                ('nombreProducto', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=100)),
            ],
        ),
    ]
